# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=50, unique=True, verbose_name='关键字')),
                ('describe', models.CharField(max_length=100, unique=True, verbose_name='描述')),
                ('content', models.TextField(null=True, verbose_name='内容')),
                ('icon', models.ImageField(null=True, upload_to='upload', verbose_name='图片')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operate_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=20, null=True, unique=True, verbose_name='分类名')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True, verbose_name='人员姓名')),
                ('password', models.CharField(max_length=200, unique=True, verbose_name='密码')),
                ('age', models.IntegerField(null=True, unique=True, verbose_name='密码')),
                ('sex', models.BooleanField(default=1, verbose_name='性别')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operate_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=200, null=True, unique=True, verbose_name='标签名')),
            ],
            options={
                'db_table': 'tag',
            },
        ),
    ]
